version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - ./backend:/app
      - /app/venv  # Exclude venv from volume mounting
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_URI=mongodb://mongodb:27017
      - OLLAMA_API_BASE=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - ./nextjs:/app
      - /app/node_modules  # Exclude node_modules from volume mounting
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8005

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=rea

volumes:
  mongodb_data:

networks:
  default:
    name: rea-network 